# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/Users/appperfect/Desktop/TeraForm/Terragrunt / terraform.tfstate.d/deployments/aws-dev-cluster/terraform.tfstate"
  }
}
